#!/bin/sh -e
# initramfs hook for recovery

PREREQS=""

# Output pre-requisites
prereqs()
{
       echo "$PREREQS"
}

case "$1" in
    prereqs)
       prereqs
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions

cp /sbin/findfs $DESTDIR/sbin/
if [ -n "$INJECT" ]; then
	. /usr/share/initramfs-tools/scripts/functions
	rm -f $DESTDIR/scripts/local-premount/ORDER
	cache_run_scripts "${DESTDIR}" "/scripts/local-premount"
fi
